media:
  - name: covers
    label: 封面图片
    input: public/covers
    output: /covers
    categories: [image]

content:
  - name: anime
    label: 番剧
    type: collection
    path: src/data/anime
    filename: "{{fields.id}}.md"
    fields:
      - { name: title, type: string, label: 标题, required: true }
      - { name: id, type: string, label: 标识符, required: true, description: "全小写字母和连字符" }
      - { name: cover, type: image, label: 封面, media: [covers] }
      - { name: tags, type: string, label: 标签, list: true }
      - { name: publishDate, type: date, label: 发布日期 }
      - { name: url, type: string, label: 外部链接 }
      - { name: type, type: string, hidden: true, default: anime }
    body: { label: 正文, type: markdown }
    view:
      fields: [title, publishDate, tags]
      sort: [publishDate desc, title asc]

  - name: manga
    label: 漫画
    type: collection
    path: src/data/manga
    filename: "{{fields.id}}.md"
    fields:
      - { name: title, type: string, label: 标题, required: true }
      - { name: id, type: string, label: 标识符, required: true, description: "全小写字母和连字符" }
      - { name: cover, type: image, label: 封面, media: [covers] }
      - { name: tags, type: string, label: 标签, list: true }
      - { name: publishDate, type: date, label: 发布日期 }
      - { name: url, type: string, label: 外部链接 }
      - { name: type, type: string, hidden: true, default: manga }
    body: { label: 正文, type: markdown }
    view:
      fields: [title, publishDate, tags]
      sort: [publishDate desc, title asc]

  - name: novel
    label: 小说
    type: collection
    path: src/data/novel
    filename: "{{fields.id}}.md"
    fields:
      - { name: title, type: string, label: 标题, required: true }
      - { name: id, type: string, label: 标识符, required: true, description: "全小写字母和连字符" }
      - { name: cover, type: image, label: 封面, media: [covers] }
      - { name: tags, type: string, label: 标签, list: true }
      - { name: publishDate, type: date, label: 发布日期 }
      - { name: url, type: string, label: 外部链接 }
      - { name: type, type: string, hidden: true, default: novel }
    body: { label: 正文, type: markdown }
    view:
      fields: [title, publishDate, tags]
      sort: [publishDate desc, title asc]

  - name: game
    label: 游戏
    type: collection
    path: src/data/game
    filename: "{{fields.id}}.md"
    fields:
      - { name: title, type: string, label: 标题, required: true }
      - { name: id, type: string, label: 标识符, required: true, description: "全小写字母和连字符" }
      - { name: cover, type: image, label: 封面, media: [covers] }
      - { name: tags, type: string, label: 标签, list: true }
      - { name: publishDate, type: date, label: 发布日期 }
      - { name: url, type: string, label: 外部链接 }
      - { name: type, type: string, hidden: true, default: game }
    body: { label: 正文, type: markdown }
    view:
      fields: [title, publishDate, tags]
      sort: [publishDate desc, title asc]
